#!/bin/sh
##
##  GNU shtool -- The GNU Portable Shell Tool
##  Copyright (c) 1994-2008 Ralf S. Engelschall <rse@engelschall.com>
##
##  See http://www.gnu.org/software/shtool/ for more information.
##  See ftp://ftp.gnu.org/gnu/shtool/ for latest version.
##
##  Version:  2.0.8 (18-Jul-2008)
##  Contents: 1/19 available modules
##

##
##  This program is free software; you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation; either version 2 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
##  General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program; if not, write to the Free Software
##  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
##  USA, or contact Ralf S. Engelschall <rse@engelschall.com>.
##
##  NOTICE: Given that you include this file verbatim into your own
##  source tree, you are justified in saying that it remains separate
##  from your package, and that this way you are simply just using GNU
##  shtool. So, in this situation, there is no requirement that your
##  package itself is licensed under the GNU General Public License in
##  order to take advantage of GNU shtool.
##

##
##  Usage: shtool [<options>] [<cmd-name> [<cmd-options>] [<cmd-args>]]
##
##  Available commands:
##    platform   Platform Identification Utility
##
##  Not available commands (because module was not built-in):
##    echo       Print string with optional construct expansion
##    mdate      Pretty-print modification time of a file or dir
##    table      Pretty-print a field-separated list as a table
##    prop       Display progress with a running propeller
##    move       Move files with simultaneous substitution
##    install    Install a program, script or datafile
##    mkdir      Make one or more directories
##    mkln       Make link with calculation of relative paths
##    mkshadow   Make a shadow tree through symbolic links
##    fixperm    Fix file permissions inside a source tree
##    rotate     Logfile rotation
##    tarball    Roll distribution tarballs
##    subst      Apply sed(1) substitution operations
##    arx        Extended archive command
##    slo        Separate linker options by library class
##    scpp       Sharing C Pre-Processor
##    version    Maintain a version information file
##    path       Deal with program paths
##

#   maximum Bourne-Shell compatibility
if [ ".$ZSH_VERSION" != . ] && (emulate sh) >/dev/null 2>&1; then
    #   reconfigure zsh(1)
    emulate sh
    NULLCMD=:
    alias -g '${1+"$@"}'='"$@"'
elif [ ".$BASH_VERSION" != . ] && (set -o posix) >/dev/null 2>&1; then
    #   reconfigure bash(1)
    set -o posix
fi

#   maximum independence of NLS nuisances
for var in \
    LANG LANGUAGE LC_ADDRESS LC_ALL LC_COLLATE LC_CTYPE LC_IDENTIFICATION \
    LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER \
    LC_TELEPHONE LC_TIME
do
    if (set +x; test -z "`(eval $var=C; export $var) 2>&1`"); then
        eval $var=C; export $var
    else
        unset $var
    fi
done

#   initial command line handling
if [ $# -eq 0 ]; then
    echo "$0:Error: invalid command line" 1>&2
    echo "$0:Hint:  run \`$0 -h' for usage" 1>&2
    exit 1
fi
if [ ".$1" = ".-h" ] || [ ".$1" = ".--help" ]; then
    echo "This is GNU shtool, version 2.0.8 (18-Jul-2008)"
    echo 'Copyright (c) 1994-2008 Ralf S. Engelschall <rse@engelschall.com>'
    echo 'Report bugs to <bug-shtool@gnu.org>'
    echo ''
    echo 'Usage: shtool [<options>] [<cmd-name> [<cmd-options>] [<cmd-args>]]'
    echo ''
    echo 'Available global <options>:'
    echo '  -v, --version   display shtool version information'
    echo '  -h, --help      display shtool usage help page (this one)'
    echo '  -d, --debug     display shell trace information'
    echo '  -r, --recreate  recreate this shtool script via shtoolize'
    echo ''
    echo 'Available <cmd-name> [<cmd-options>] [<cmd-args>]:'
    echo '  platform [-F|--format <format>] [-S|--sep <string>] [-C|--conc'
    echo '           <string>] [-L|--lower] [-U|--upper] [-v|--verbose]'
    echo '           [-c|--concise] [-n|--no-newline] [-t|--type <type>]'
    echo '           [-V|--version] [-h|--help]'
    echo ''
    echo 'Not available <cmd-name> (because module was not built-in):'
    echo '  echo     [-n|--newline] [-e|--expand] [<string> ...]'
    echo '  mdate    [-n|--newline] [-z|--zero] [-s|--shorten] [-d|--digits]'
    echo '           [-f|--field-sep <str>] [-o|--order <spec>] <path>'
    echo '  table    [-F|--field-sep <sep>] [-w|--width <width>] [-c|--columns'
    echo '           <cols>] [-s|--strip <strip>] <str><sep><str>...'
    echo '  prop     [-p|--prefix <str>]'
    echo '  move     [-v|--verbose] [-t|--trace] [-e|--expand] [-p|--preserve]'
    echo '           <src-file> <dst-file>'
    echo '  install  [-v|--verbose] [-t|--trace] [-d|--mkdir] [-c|--copy]'
    echo '           [-C|--compare-copy] [-s|--strip] [-m|--mode <mode>]'
    echo '           [-o|--owner <owner>] [-g|--group <group>] [-e|--exec'
    echo '           <sed-cmd>] <file> [<file> ...] <path>'
    echo '  mkdir    [-t|--trace] [-f|--force] [-p|--parents] [-m|--mode'
    echo '           <mode>] [-o|--owner <owner>] [-g|--group <group>] <dir>'
    echo '           [<dir> ...]'
    echo '  mkln     [-t|--trace] [-f|--force] [-s|--symbolic] <src-path>'
    echo '           [<src-path> ...] <dst-path>'
    echo '  mkshadow [-v|--verbose] [-t|--trace] [-a|--all] <src-dir> <dst-dir>'
    echo '  fixperm  [-v|--verbose] [-t|--trace] <path> [<path> ...]'
    echo '  rotate   [-v|--verbose] [-t|--trace] [-f|--force] [-n|--num-files'
    echo '           <count>] [-s|--size <size>] [-c|--copy] [-r|--remove]'
    echo '           [-a|--archive-dir <dir>] [-z|--compress [<tool>:]<level>]'
    echo '           [-b|--background] [-d|--delay] [-p|--pad <len>] [-m|--mode'
    echo '           <mode>] [-o|--owner <owner>] [-g|--group <group>] [-M|--migrate'
    echo '           <cmd>] [-P|--prolog <cmd>] [-E|--epilog <cmd>] <file> [...]'
    echo '  tarball  [-t|--trace] [-v|--verbose] [-o|--output <tarball>]'
    echo '           [-c|--compress <prog>] [-d|--directory <dir>] [-u|--user'
    echo '           <user>] [-g|--group <group>] [-e|--exclude <pattern>]'
    echo '           <path> [<path> ...]'
    echo '  subst    [-v|--verbose] [-t|--trace] [-n|--nop] [-w|--warning]'
    echo '           [-q|--quiet] [-s|--stealth] [-i|--interactive] [-b|--backup'
    echo '           <ext>] [-e|--exec <cmd>] [-f|--file <cmd-file>] [<file>]'
    echo '           [...]'
    echo '  arx      [-t|--trace] [-C|--command <cmd>] <op> <archive> [<file>'
    echo '           ...]'
    echo '  slo      [-p|--prefix <str>] -- -L<dir> -l<lib> [-L<dir> -l<lib>'
    echo '           ...]'
    echo '  scpp     [-v|--verbose] [-p|--preserve] [-f|--filter <filter>]'
    echo '           [-o|--output <ofile>] [-t|--template <tfile>] [-M|--mark'
    echo '           <mark>] [-D|--define <dname>] [-C|--class <cname>]'
    echo '           <file> [<file> ...]'
    echo '  version  [-l|--language <lang>] [-n|--name <name>] [-p|--prefix'
    echo '           <prefix>] [-s|--set <version>] [-e|--edit] [-i|--increase'
    echo '           <knob>] [-d|--display <type>] <file>'
    echo '  path     [-s|--suppress] [-r|--reverse] [-d|--dirname] [-b|--basename]'
    echo '           [-m|--magic] [-p|--path <path>] <str> [<str> ...]'
    echo ''
    exit 0
fi
if [ ".$1" = ".-v" ] || [ ".$1" = ".--version" ]; then
    echo "GNU shtool 2.0.8 (18-Jul-2008)"
    exit 0
fi
if [ ".$1" = ".-r" ] || [ ".$1" = ".--recreate" ]; then
    shtoolize -oshtool platform
    exit 0
fi
if [ ".$1" = ".-d" ] || [ ".$1" = ".--debug" ]; then
    shift
    set -x
fi
name=`echo "$0" | sed -e 's;.*/\([^/]*\)$;\1;' -e 's;-sh$;;' -e 's;\.sh$;;'`
case "$name" in
    platform )
        #   implicit tool command selection
        tool="$name"
        ;;
    * )
        #   explicit tool command selection
        tool="$1"
        shift
        ;;
esac
arg_spec=""
opt_spec=""
gen_tmpfile=no

##
##  DISPATCH INTO SCRIPT PROLOG
##

case $tool in
    platform )
        str_tool="platform"
        str_usage="[-F|--format <format>] [-S|--sep <string>] [-C|--conc <string>] [-L|--lower] [-U|--upper] [-v|--verbose] [-c|--concise] [-n|--no-newline] [-t|--type <type>] [-V|--version] [-h|--help]"
        arg_spec="0="
        opt_spec="F:S:C:L.U.v.c.n.t:d.V.h."
        opt_alias="F:format,S:sep,C:conc,L:lower,U:upper,v:verbose,c:consise,t:type,n:no-newline,V:version,h:help"
        opt_F="%{sp} (%{ap})"
        opt_S=" "
        opt_C="/"
        opt_L=no
        opt_U=no
        opt_t=""
        opt_v=no
        opt_c=no
        opt_n=no
        opt_V=no
        opt_h=no
        ;;
    -* )
        echo "$0:Error: unknown option \`$tool'" 2>&1
        echo "$0:Hint:  run \`$0 -h' for usage" 2>&1
        exit 1
        ;;
    * )
        echo "$0:Error: unknown command \`$tool'" 2>&1
        echo "$0:Hint:  run \`$0 -h' for usage" 2>&1
        exit 1
        ;;
esac

##
##  COMMON UTILITY CODE
##

#   commonly used ASCII values
ASC_TAB="	"
ASC_NL="
"

#   determine name of tool
if [ ".$tool" != . ]; then
    #   used inside shtool script
    toolcmd="$0 $tool"
    toolcmdhelp="shtool $tool"
    msgprefix="shtool:$tool"
else
    #   used as standalone script
    toolcmd="$0"
    toolcmdhelp="sh $0"
    msgprefix="$str_tool"
fi

#   parse argument specification string
eval `echo $arg_spec |\
      sed -e 's/^\([0-9]*\)\([+=]\)/arg_NUMS=\1; arg_MODE=\2/'`

#   parse option specification string
eval `echo h.$opt_spec |\
      sed -e 's/\([a-zA-Z0-9]\)\([.:+]\)/opt_MODE_\1=\2;/g'`

#   parse option alias string
eval `echo h:help,$opt_alias |\
      sed -e 's/-/_/g' -e 's/\([a-zA-Z0-9]\):\([^,]*\),*/opt_ALIAS_\2=\1;/g'`

#   interate over argument line
opt_PREV=''
while [ $# -gt 0 ]; do
    #   special option stops processing
    if [ ".$1" = ".--" ]; then
        shift
        break
    fi

    #   determine option and argument
    opt_ARG_OK=no
    if [ ".$opt_PREV" != . ]; then
        #   merge previous seen option with argument
        opt_OPT="$opt_PREV"
        opt_ARG="$1"
        opt_ARG_OK=yes
        opt_PREV=''
    else
        #   split argument into option and argument
        case "$1" in
            --[a-zA-Z0-9]*=*)
                eval `echo "x$1" |\
                      sed -e 's/^x--\([a-zA-Z0-9-]*\)=\(.*\)$/opt_OPT="\1";opt_ARG="\2"/'`
                opt_STR=`echo $opt_OPT | sed -e 's/-/_/g'`
                eval "opt_OPT=\${opt_ALIAS_${opt_STR}-${opt_OPT}}"
                ;;
            --[a-zA-Z0-9]*)
                opt_OPT=`echo "x$1" | cut -c4-`
                opt_STR=`echo $opt_OPT | sed -e 's/-/_/g'`
                eval "opt_OPT=\${opt_ALIAS_${opt_STR}-${opt_OPT}}"
                opt_ARG=''
                ;;
            -[a-zA-Z0-9]*)
                eval `echo "x$1" |\
                      sed -e 's/^x-\([a-zA-Z0-9]\)/opt_OPT="\1";/' \
                          -e 's/";\(.*\)$/"; opt_ARG="\1"/'`
                ;;
            -[a-zA-Z0-9])
                opt_OPT=`echo "x$1" | cut -c3-`
                opt_ARG=''
                ;;
            *)
                break
                ;;
        esac
    fi

    #   eat up option
    shift

    #   determine whether option needs an argument
    eval "opt_MODE=\$opt_MODE_${opt_OPT}"
    if [ ".$opt_ARG" = . ] && [ ".$opt_ARG_OK" != .yes ]; then
        if [ ".$opt_MODE" = ".:" ] || [ ".$opt_MODE" = ".+" ]; then
            opt_PREV="$opt_OPT"
            continue
        fi
    fi

    #   process option
    case $opt_MODE in
        '.' )
            #   boolean option
            eval "opt_${opt_OPT}=yes"
            ;;
        ':' )
            #   option with argument (multiple occurances override)
            eval "opt_${opt_OPT}=\"\$opt_ARG\""
            ;;
        '+' )
            #   option with argument (multiple occurances append)
            eval "opt_${opt_OPT}=\"\$opt_${opt_OPT}\${ASC_NL}\$opt_ARG\""
            ;;
        * )
            echo "$msgprefix:Error: unknown option: \`$opt_OPT'" 1>&2
            echo "$msgprefix:Hint:  run \`$toolcmdhelp -h' or \`man shtool' for details" 1>&2
            exit 1
            ;;
    esac
done
if [ ".$opt_PREV" != . ]; then
    echo "$msgprefix:Error: missing argument to option \`$opt_PREV'" 1>&2
    echo "$msgprefix:Hint:  run \`$toolcmdhelp -h' or \`man shtool' for details" 1>&2
    exit 1
fi

#   process help option
if [ ".$opt_h" = .yes ]; then
    echo "Usage: $toolcmdhelp $str_usage"
    exit 0
fi

#   complain about incorrect number of arguments
case $arg_MODE in
    '=' )
        if [ $# -ne $arg_NUMS ]; then
            echo "$msgprefix:Error: invalid number of arguments (exactly $arg_NUMS expected)" 1>&2
            echo "$msgprefix:Hint:  run \`$toolcmd -h' or \`man shtool' for details" 1>&2
            exit 1
        fi
        ;;
    '+' )
        if [ $# -lt $arg_NUMS ]; then
            echo "$msgprefix:Error: invalid number of arguments (at least $arg_NUMS expected)" 1>&2
            echo "$msgprefix:Hint:  run \`$toolcmd -h' or \`man shtool' for details" 1>&2
            exit 1
        fi
        ;;
esac

#   establish a temporary file on request
if [ ".$gen_tmpfile" = .yes ]; then
    #   create (explicitly) secure temporary directory
    if [ ".$TMPDIR" != . ]; then
        tmpdir="$TMPDIR"
    elif [ ".$TEMPDIR" != . ]; then
        tmpdir="$TEMPDIR"
    else
        tmpdir="/tmp"
    fi
    tmpdir="$tmpdir/.shtool.$$"
    ( umask 077
      rm -rf "$tmpdir" >/dev/null 2>&1 || true
      mkdir  "$tmpdir" >/dev/null 2>&1
      if [ $? -ne 0 ]; then
          echo "$msgprefix:Error: failed to create temporary directory \`$tmpdir'" 1>&2
          exit 1
      fi
    )

    #   create (implicitly) secure temporary file
    tmpfile="$tmpdir/shtool.tmp"
    touch "$tmpfile"
fi

#   utility function: map string to lower case
util_lower () {
    echo "$1" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz'
}

#   utility function: map string to upper case
util_upper () {
    echo "$1" | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
}

#   cleanup procedure
shtool_exit () {
    rc="$1"
    if [ ".$gen_tmpfile" = .yes ]; then
        rm -rf "$tmpdir" >/dev/null 2>&1 || true
    fi
    exit $rc
}

##
##  DISPATCH INTO SCRIPT BODY
##

case $tool in

platform )
    ##
    ##  platform -- Platform Identification Utility
    ##  Copyright (c) 2003-2008 Ralf S. Engelschall <rse@engelschall.com>
    ##

    #   option post-processing
    if [ ".$opt_t" != . ]; then
        case "$opt_t" in
            binary )
                #   binary package id (OpenPKG RPM)
                opt_F="%<ap>-%<sp>"
                opt_L=yes
                opt_S=""
                opt_C="+"
                ;;
            build )
                #   build time checking (OpenPKG RPM)
                opt_F="%<at>-%<st>"
                opt_L=yes
                opt_S=""
                opt_C="+"
                ;;
            gnu )
                #   GNU config.guess style <arch>-<vendor>-<os><osversion>
                opt_F="%<at>-unknown-%<st>"
                opt_L=yes
                opt_S=""
                opt_C="+"
                ;;
            web )
                #   non-whitespace HTTP Server-header id
                opt_F="%<sp>-%<ap>"
                opt_S="/"
                opt_C="+"
                ;;
            summary)
                #   human readable verbose summary information
                opt_F="Class:      %[sc] (%[ac])\\nProduct:    %[sp] (%[ap])\\nTechnology: %[st] (%[at])"
                opt_S=" "
                opt_C="/"
                ;;
            all-in-one )
                #   full-table all-in-one information
                opt_F=""
                opt_F="${opt_F}concise architecture class:      %<ac>\\n"
                opt_F="${opt_F}regular architecture class:      %{ac}\\n"
                opt_F="${opt_F}verbose architecture class:      %[ac]\\n"
                opt_F="${opt_F}concise architecture product:    %<ap>\\n"
                opt_F="${opt_F}regular architecture product:    %{ap}\\n"
                opt_F="${opt_F}verbose architecture product:    %[ap]\\n"
                opt_F="${opt_F}concise architecture technology: %<at>\\n"
                opt_F="${opt_F}regular architecture technology: %{at}\\n"
                opt_F="${opt_F}verbose architecture technology: %[at]\\n"
                opt_F="${opt_F}concise system class:            %<sc>\\n"
                opt_F="${opt_F}regular system class:            %{sc}\\n"
                opt_F="${opt_F}verbose system class:            %[sc]\\n"
                opt_F="${opt_F}concise system product:          %<sp>\\n"
                opt_F="${opt_F}regular system product:          %{sp}\\n"
                opt_F="${opt_F}verbose system product:          %[sp]\\n"
                opt_F="${opt_F}concise system technology:       %<st>\\n"
                opt_F="${opt_F}regular system technology:       %{st}\\n"
                opt_F="${opt_F}verbose system technology:       %[st]"
                ;;
            * )
                echo "$msgprefix:Error: invalid type \`$opt_t'" 1>&2
                exit 1
                ;;
        esac
    fi

    #   assemble initial platform information
    UNAME_MACHINE=`(uname -m) 2>/dev/null` ||\
    UNAME_MACHINE=`(uname -p) 2>/dev/null` ||\
    UNAME_MACHINE='unknown'
    UNAME_SYSTEM=`(uname -s) 2>/dev/null`  ||\
    UNAME_SYSTEM='unknown'
    UNAME_RELEASE=`(uname -r) 2>/dev/null` ||\
    UNAME_RELEASE=`(uname -v) 2>/dev/null` ||\
    UNAME_RELEASE='unknown'

    UNAME="${UNAME_MACHINE}:${UNAME_SYSTEM}:${UNAME_RELEASE}"

    AC=""; AP=""; AT=""
    SC=""; SP=""; ST=""

    #    dispatch into platform specific sections
    case "${UNAME}" in

        #   FreeBSD
        *:FreeBSD:* )
            #   determine architecture
            AC="${UNAME_MACHINE}"
            case "${AC}" in
                i386 ) AC="iX86" ;;
            esac
            AP="${AC}"
            AT="${AP}"
            if [ ".${AT}" = ".iX86" ]; then
                case "`(/sbin/sysctl -n hw.model) 2>&1`" in
                    *"Xeon"* | *"Pentium Pro"* | *"Cyrix 6x86MX"* | *"Pentium II"* | *"Pentium III"* | *"Pentium 4"* | *"Celeron"* ) AT="i686" ;;
                    *"Pentium"* ) AT="i586" ;; *"i486[SD]X"* | *"Cyrix 486"* | *"Cyrix [56]x86"* | *"Blue Lightning" | *"Cyrix 486S/DX" ) AT="i486" ;;
                    *"i386[SD]X"* | *"NexGen 586"* ) AT="i386" ;;
                esac
            fi
            #   determine system
            r=`echo "${UNAME_RELEASE}" |\
               sed -e 's;[()];;' -e 's/\(-.*\)$/[\1]/'`
            ST="FreeBSD ${r}"
            SP="${ST}"
            case "${r}" in
                1.* ) SC="4.3BSD" ;;
                *   ) SC="4.4BSD" ;;
            esac
            ;;

        #   NetBSD
        *:NetBSD:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            AP="${AT}"
            case "${AP}" in
                i[3-6]86 ) AP="iX86" ;;
            esac
            AC="${AP}"
            #   determine system
            r=`echo "${UNAME_RELEASE}" | sed -e 's/\([-_].*\)$/[\1]/'`
            ST="NetBSD ${r}"
            SP="${ST}"
            case "${r}" in
                0.* ) SC="4.3BSD" ;;
                *   ) SC="4.4BSD" ;;
            esac
            ;;

        #   OpenBSD
        *:OpenBSD:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            AP="${AT}"
            case "${AP}" in
                i[3-6]86 ) AP="iX86" ;;
            esac
            AC="${AP}"
            #   determine system
            r=`echo "${UNAME_RELEASE}" | sed -e 's/\([-_].*\)$/[\1]/'`
            ST="OpenBSD ${r}"
            SP="${ST}"
            SC="4.4BSD"
            ;;

        #   DragonFly BSD
        *:DragonFly:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            AP="${AT}"
            case "${AP}" in
                i[3-6]86 ) AP="iX86" ;;
            esac
            AC="${AP}"
            #   determine system
            r=`echo "${UNAME_RELEASE}" | sed -e 's/\([-_].*\)$/[\1]/'`
            ST="DragonFly ${r}"
            SP="${ST}"
            SC="4.4BSD"
            ;;

        #   GNU/Linux
        *:Linux:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            case "${AT}" in
               ia64     ) AT="IA64"   ;;
               x86_64   ) AT='AMD64'  ;;
               parisc   ) AT="HPPA32" ;;
               parisc64 ) AT="HPPA64" ;;
            esac
            AP="${AT}"
            case "${AP}" in
               i[3-6]86 ) AP='iX86' ;;
            esac
            AC="${AP}"
            #   determine system
            v_kern=`echo "${UNAME_RELEASE}" |\
                sed -e 's/^\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
            v_libc=`(strings /lib/libc.so.* | grep '^GLIBC_' | sed -e 's/^GLIBC_//' |\
                env -i sort -n | sed -n -e '$p' | sed -e 's/^\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/') 2>/dev/null`
            ST="GNU/<Linux >${v_libc}/<${v_kern}>"
            if [ -f /etc/lsb-release ]; then
                eval `( . /etc/lsb-release
                    echo "SC=\"LSB${LSB_VERSION}\""
                    if [ ".${DISTRIB_ID}" != . -a ".${DISTRIB_RELEASE}" != . ]; then
                        echo "SP=\"${DISTRIB_ID} ${DISTRIB_RELEASE}\""
                    fi
                ) 2>/dev/null`
            fi
            if [ ".$SP" = . ]; then
                for tagfile in x \
                    `cd /etc && \
                    /bin/ls *[_-]release *[_-]version 2>/dev/null | env -i sort | \
                    sed -e '/^redhat-release$/d' -e '/^lsb-release$/d'; \
                    echo redhat-release lsb-release`
                do
                    [ ".${tagfile}" = .x ] && continue
                    [ ! -f "/etc/${tagfile}" ] && continue
                    n=`echo ${tagfile} | sed -e 's/[_-]release$//' -e 's/[_-]version$//'`
                    v=`(grep VERSION /etc/${tagfile}; cat /etc/${tagfile}) | grep '[0-9]' | sed -e 'q' |\
                       sed -e 's/^/#/' \
                           -e 's/^#[^0-9]*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*$/\1/' \
                           -e 's/^#[^0-9]*\([0-9][0-9]*\.[0-9][0-9]*\).*$/\1/' \
                           -e 's/^#[^0-9]*\([0-9][0-9]*\).*$/\1/' \
                           -e 's/^#.*$//'`
                    case "`util_lower ${n}`" in
                        redhat )
                            if [ ".`egrep '(Red Hat Enterprise Linux|CentOS)' /etc/${tagfile}`" != . ]; then
                                n="<R>ed <H>at <E>nterprise <L>inux"
                            else
                                n="<R>ed <H>at <L>inux"
                            fi
                            ;;
                        debian             ) n="Debian[ GNU/Linux]"        ;;
                        ubuntu             ) n="Ubuntu[ GNU/Linux]"        ;;
                        fedora             ) n="<Fedora> Core[ GNU/Linux]" ;;
                        suse               ) n="[Novell ]SUSE[ Linux]"     ;;
                        mandrake*|mandriva ) n="Mandriva[ Linux]"          ;;
                        gentoo             ) n="Gentoo[ GNU/Linux]"        ;;
                        slackware          ) n="Slackware[ Linux]"         ;;
                        turbolinux         ) n="TurboLinux"                ;;
                        unitedlinux        ) n="UnitedLinux"               ;;
                        *                  ) n="${n}[ GNU/Linux]"          ;;
                    esac
                    case "$n" in
                        *"<"*">"* ) SP="$n <$v>" ;;
                        *         ) SP="$n $v"   ;;
                    esac
                    break
                done
            fi
            [ ".$SP" = . ] && SP="${ST}"
            [ ".$SC" = . ] && SC="LSB"
            ;;

        #   Sun Solaris
        *:SunOS:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            case "${AT}" in
                i86pc )
                    AT="iX86"
                    case "`(/bin/isainfo -k) 2>&1`" in
                        amd64 ) AT="AMD64" ;;
                    esac
                    ;;
            esac
            AP="${AT}"
            case "${AP}" in
                sun4[cdm] ) AP="SPARC32" ;;
                sun4[uv]  ) AP="SPARC64" ;;
                sun4*     ) AP="SPARC"   ;;
            esac
            AC="${AP}"
            case "${AC}" in
                SPARC* ) AC="SPARC" ;;
            esac
            #   determine system
            ST="[Sun ]SunOS ${UNAME_RELEASE}"
            v=`echo "${UNAME_RELEASE}" |\
               sed -e 's;^4\.;1.;' \
                   -e 's;^5\.\([0-6]\)[^0-9]*$;2.\1;' \
                   -e 's;^5\.\([0-9][0-9]*\).*;\1;'`
            SP="[Sun ]Solaris $v"
            case "${UNAME_RELEASE}" in
                4.* ) SC="4.3BSD" ;;
                5.* ) SC="SVR4"   ;;
            esac
            ;;

        #   SCO UnixWare
        *:UnixWare:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            case "${AT}" in
                i[3-6]86 | ix86at ) AT="iX86" ;;
            esac
            AP="${AT}"
            #   determine system
            v=`/sbin/uname -v`
            ST="[SCO ]UnixWare ${v}"
            SP="${ST}"
            SC="SVR${UNAME_RELEASE}"
            ;;

        #   QNX
        *:QNX:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            case "${AT}" in
                x86pc ) AT="iX86" ;;
            esac
            AP="${AT}"
            #   determine system
            v="${UNAME_RELEASE}"
            ST="QNX[ Neutrino RTOS] ${v}"
            v=`echo "${v}" | sed -e 's;^\([0-9][0-9]*\.[0-9][0-9]*\).*$;\1;'`
            SP="QNX[ Neutrino RTOS] ${v}"
            SC="QNX"
            ;;

        #   SGI IRIX
        *:IRIX*:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            AP="${AT}"
            case "${AP}:${UNAME_SYSTEM}" in
                IP*:IRIX64 ) AP="MIPS64" ;;
                IP*:*      ) AP="MIPS"   ;;
            esac
            AC="${AP}"
            #   determine system
            v=`(/bin/uname -R || /bin/uname -r) 2>/dev/null | sed -e 's;[0-9.]* ;;'`
            ST="[SGI ]IRIX ${v}"
            v="${UNAME_RELEASE}"
            SP="[SGI ]IRIX ${v}"
            SC="4.2BSD/SVR3"
            ;;

        #   HP HP-UX
        *:HP-UX:* )
            #   determine architecture
            AT="${UNAME_MACHINE}"
            case "${AT}" in
                ia64 ) AT="IA64" ;;
                9000/[34]?? ) AT=M68K ;;
                9000/[678][0-9][0-9])
                    sc_cpu_version=`/usr/bin/getconf SC_CPU_VERSION 2>/dev/null`
                    sc_kernel_bits=`/usr/bin/getconf SC_KERNEL_BITS 2>/dev/null`
                    case "${sc_cpu_version}" in
                        523 ) AT="HPPA1.0" ;;
                        528 ) AT="HPPA1.1" ;;
                        532 ) AT="HPPA2.0"
                            case "${sc_kernel_bits}" in
                                32 ) AT="${AT}n" ;;
                                64 ) AT="${AT}w" ;;
                            esac
                            ;;
                    esac
                    ;;
            esac
            AP="${AT}"
            case "${AP}" in
                HPPA* ) AP="HPPA" ;;
            esac
            AC="${AP}"
            #   determine system
            v=`echo "${UNAME_RELEASE}" | sed -e 's;^[^0-9]*;;'`
            ST="[HP ]<HP>-<UX ${v}>"
            SP="${ST}"
            case "${v}" in
                10.*   ) SC="SVR4.2" ;;
                [7-9]* ) SC="SVR4"   ;;
            esac
            ;;

        #   HP Tru64 (OSF1)
        *:OSF1:* )
            #   determine architecture
            AP="${UNAME_MACHINE}"
            case "${AP}" in
                alpha ) AP="Alpha" ;;
            esac
            alpha_type=`(/usr/sbin/psrinfo -v) 2>/dev/null |\
                sed -n -e 's/^.*The alpha \([^ ][^ ]*\).*processor.*$/\1/p' | sed -e 'q'`
            AT="${AP}${alpha_type}"
            AC="${AP}"
            #   determine system
            v=`echo "${UNAME_RELEASE}" | sed -e 's;^[VTX];;'`
            ST="[HP ]Tru64 ${v}"
            SP="${ST}"
            SC="OSF1"
            ;;

        #   IBM AIX
        *:AIX:* )
            #   determine architecture
            cpu_arch=RS6000
            if [ -x /usr/sbin/lsdev -a -x /usr/sbin/lsattr ]; then
                cpu_id=`/usr/sbin/lsdev -C -c processor -S available | sed 1q | awk '{ print $1 }'`
                if [ ".`/usr/sbin/lsattr -El ${cpu_id} | grep -i powerpc`" != . ]; then
                    cpu_arch=PPC
                fi
            elif [ -d /QOpenSys ]; then
                #   IBM i5/OS (aka OS/400) with PASE (Portable Application Solutions Environment)
                cpu_arch=PPC
            fi
            if [ -x /usr/bin/oslevel ]; then
                os_level=`/usr/bin/oslevel`
            else
                os_level="`uname -v`.`uname -r`"
            fi
            os_level=`echo "${os_level}" |\
                      sed -e 's;^\([0-9][0-9]*\.[0-9][0-9]*\)\(\.[0-9][0-9]*\)\(.*\)$;<\1>\2[\3];' \
                          -e 's;^\([0-9][0-9]*\.[0-9][0-9]*\)\(.*\)$;<\1>\2;'`
            AT="${cpu_arch}"
            AP="${AT}"
            AC="${AP}"
            #   determine system
            ST="[IBM ]<AIX >${os_level}"
            SP="${ST}"
            case "${os_level}" in
                [12]* ) SC="SVR2" ;;
                *     ) SC="SVR4" ;;
            esac
            ;;

        #   Apple Mac OS X (Darwin)
        *:Darwin:* )
            #   determine architecture
            AT="`uname -p`"
            case "${AT}" in
                powerpc ) AT="PPC" ;;
            esac
            AP="${AT}"
            case "${AP}" in
                i?86 ) AP="iX86" ;;
            esac
            AC="${AP}"
            #   determine system
            unset v1; unset v2; unset v3
            eval `echo "${UNAME_RELEASE}" |\
                  sed -e 's/^/#/' \
                      -e 's/^#\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*$/v1="\1"; v2="\2"; v3="\3"/' \
                      -e 's/^#\([0-9][0-9]*\)\.\([0-9][0-9]*\).*$/v1="\1"; v2="\2"/' \
                      -e 's/^#\([0-9][0-9]*\).*$/v1="\1"/' \
                      -e 's/^#.*$/v1="0"/'`
            ST="[Apple ]<${UNAME_SYSTEM} ${v1}>${v2+.$v2}${v3+[.$v3]}"
            SP="$ST"
            v="`(sw_vers) 2>/dev/null | grep 'ProductVersion:' | sed -e 's/^ProductVersion:[^0-9]*\([0-9][0-9.]*\).*$/\1/'`"
            if [ ".$v" = . ]; then
                for name in System Server; do
                    if [ -f /System/Library/CoreServices/${name}Version.plist ]; then
                        v=`(defaults read "/System/Library/CoreServices/${name}Version" "ProductVersion") 2>/dev/null`
                        [ ".$v" != . ] && break
                    fi
                done
            fi
            if [ ".$v" != . ]; then
                unset v1; unset v2; unset v3
                eval `echo "${v}" |\
                      sed -e 's/^/#/' \
                          -e 's/^#\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*$/v1="\1"; v2="\2"; v3="\3"/' \
                          -e 's/^#\([0-9][0-9]*\)\.\([0-9][0-9]*\).*$/v1="\1"; v2="\2"/' \
                          -e 's/^#\([0-9][0-9]*\).*$/v1="\1"/' \
                          -e 's/^#.*$/v1="0"/'`
                SP="[Apple ]Mac OS X ${v1}${v2+.$v2}${v3+[.$v3]}"
            fi
            SC="4.4BSD/Mach3.0"
            ;;

        #   Windows/Cygwin
        *:CYGWIN*:* )
            #   determine architecture
            AT="`uname -m`"
            AP="${AT}"
            case "${AP}" in
                i?86 ) AP="iX86" ;;
            esac
            AC="${AP}"
            #   determine system
            unset v1; unset v2; unset v3
            eval `echo "${UNAME_RELEASE}" |\
                  sed -e 's/^/#/' \
                      -e 's/^#\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*$/v1="\1"; v2="\2"; v3="\3"/' \
                      -e 's/^#\([0-9][0-9]*\)\.\([0-9][0-9]*\).*$/v1="\1"; v2="\2"/' \
                      -e 's/^#\([0-9][0-9]*\).*$/v1="\1"/' \
                      -e 's/^#.*$/v1="0"/'`
            ST="Cygwin ${v1}${v2+.$v2}${v3+[.$v3]}"
            SP="$ST"
            SC="Windows"
            v=`echo "${UNAME_SYSTEM}" | sed -e 's/^CYGWIN_NT-//' |\
               sed -e 's/^/#/' -e 's/^#\([0-9][0-9]*\.[0-9][0-9]*\).*$/\1/' -e 's/^#.*$//'`
            case "$v" in
                4.0 ) SC="$SC[ NT]"    ;;
                5.0 ) SC="$SC[ 2000]"  ;;
                5.1 ) SC="$SC[ XP]"    ;;
                6.0 ) SC="$SC[ Vista]" ;;
            esac
            ;;

        #   TODO ...ADD YOUR NEW PLATFORM CHECK HERE... TODO
        # *:XXX:* )
        #   ...
        #   ;;

        #   ...A STILL UNKNOWN PLATFORM...
        * )
            AT=`echo "${UNAME_MACHINE}" | sed -e "s; ;${opt_C};g"`
            AP="${AT}"
            AC="${AP}"
            v=`echo "${UNAME_RELEASE}" |\
               sed -e 's/^/#/' \
                   -e 's/^#[^0-9]*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*$/\1/' \
                   -e 's/^#[^0-9]*\([0-9][0-9]*\.[0-9][0-9]*\).*$/\1/' \
                   -e 's/^#[^0-9]*\([0-9][0-9]*\).*$/\1/' \
                   -e 's/^#.*$/?/'`
            ST="${UNAME_SYSTEM} ${v}"
            SP="${ST}"
            SC="${SP}"
            ;;

    esac

    #   provide fallback values
    [ ".$AT" = . ] && AT="${AP:-${AC}}"
    [ ".$AP" = . ] && AP="${AT:-${AC}}"
    [ ".$AC" = . ] && AC="${AP:-${AT}}"
    [ ".$ST" = . ] && ST="${SP:-${SC}}"
    [ ".$SP" = . ] && SP="${ST:-${SC}}"
    [ ".$SC" = . ] && SC="${SP:-${ST}}"

    #   support explicit enforced verbose/concise output
    if [ ".$opt_v" = .yes ]; then
        opt_F=`echo ":$opt_F" | sed -e 's/^://' -e 's/%\([as][cpt]\)/%[\1]/g'`
    elif [ ".$opt_c" = .yes ]; then
        opt_F=`echo ":$opt_F" | sed -e 's/^://' -e 's/%\([as][cpt]\)/%<\1>/g'`
    fi

    #   provide verbose and concise variants
    AC_V=""; AC_N=""; AC_C=""
    AP_V=""; AP_N=""; AP_C=""
    AT_V=""; AT_N=""; AT_C=""
    SC_V=""; SC_N=""; SC_C=""
    SP_V=""; SP_N=""; SP_C=""
    ST_V=""; ST_N=""; ST_C=""
    for var_lc in at ap ac st sp sc; do
        case "$opt_F" in
            *"%[${val_lc}]"* | *"%{${val_lc}}"* | *"%${val_lc}"* | *"%<${val_lc}>"* )
            var_uc=`util_upper "$var_lc"`
            eval "val=\"\$${var_uc}\""
            val_V=""; val_N=""; val_C=""
            case "$opt_F" in
                *"%[${var_lc}]"* )
                    val_V=`echo ":$val" | \
                           sed -e 's/^://' \
                               -e 's;\[\([^]]*\)\];\1;g' \
                               -e 's;<\([^>]*\)>;\1;g' \
                               -e "s; ;§§;g" \
                               -e "s;/;%%;g" \
                               -e "s;§§;${opt_S};g" \
                               -e "s;%%;${opt_C};g"`
                    eval "${var_uc}_V=\"\${val_V}\""
                    ;;
            esac
            case "$opt_F" in
                *"%{${var_lc}}"* | *"%${var_lc}"* )
                    val_N=`echo ":$val" | \
                           sed -e 's/^://' \
                               -e 's;\[\([^]]*\)\];;g' \
                               -e 's;<\([^>]*\)>;\1;g' \
                               -e "s; ;§§;g" \
                               -e "s;/;%%;g" \
                               -e "s;§§;${opt_S};g" \
                               -e "s;%%;${opt_C};g"`
                    eval "${var_uc}_N=\"\${val_N}\""
                    ;;
            esac
            case "$opt_F" in
                *"%<${var_lc}>"* )
                    val_C=`echo ":$val" | \
                           sed -e 's/^://' \
                               -e 's;\[\([^]]*\)\];;g' \
                               -e 's;[^<]*<\([^>]*\)>[^<]*;\1;g' \
                               -e "s; ;§§;g" \
                               -e "s;/;%%;g" \
                               -e "s;§§;${opt_S};g" \
                               -e "s;%%;${opt_C};g"`
                    eval "${var_uc}_C=\"\${val_C}\""
                    ;;
            esac
            ;;
        esac
    done

    #   create output string
    output=`echo ":$opt_F" |\
            sed -e "s/^://" \
                -e "s;%\\[ac\\];${AC_V};g" \
                -e "s;%{ac};${AC_N};g" \
                -e "s;%ac;${AC_N};g" \
                -e "s;%<ac>;${AC_C};g" \
                -e "s;%\\[ap\\];${AP_V};g" \
                -e "s;%{ap};${AP_N};g" \
                -e "s;%ap;${AP_N};g" \
                -e "s;%<ap>;${AP_C};g" \
                -e "s;%\\[at\\];${AT_V};g" \
                -e "s;%{at};${AT_N};g" \
                -e "s;%at;${AT_N};g" \
                -e "s;%<at>;${AT_C};g" \
                -e "s;%\\[sc\\];${SC_V};g" \
                -e "s;%{sc};${SC_N};g" \
                -e "s;%sc;${SC_N};g" \
                -e "s;%<sc>;${SC_C};g" \
                -e "s;%\\[sp\\];${SP_V};g" \
                -e "s;%{sp};${SP_N};g" \
                -e "s;%sp;${SP_N};g" \
                -e "s;%<sp>;${SP_C};g" \
                -e "s;%\\[st\\];${ST_V};g" \
                -e "s;%{st};${ST_N};g" \
                -e "s;%st;${ST_N};g" \
                -e "s;%<st>;${ST_C};g" \
                -e 's/\\\\n/^/g' |\
             tr '^' '\012'`

    #   support lower/upper-case mapping
    if [ ".$opt_L" = .yes ]; then
        output=`util_lower "$output"`
    elif [ ".$opt_U" = .yes ]; then
        output=`util_upper "$output"`
    fi

    #   display output string
    if [ ".$opt_n" = .yes ]; then
        echo . | awk '{ printf("%s", output); }' output="$output"
    else
        echo "$output"
    fi

    shtool_exit 0
    ;;

esac

shtool_exit 0

